### ISSUE TITLE
shutdown not working

### ISSUE THREAD

**Issue by bali888888** [ducnm9/Hackintosh-Intel-i5-10400-Asrock-B460M-Steel-Legend#10]
shutdown is not working, and when you shutdown, it actually restart.

Even use hackintool to re do usb mapping, the issue still exist.

Is there any way to fix the problem?

**Comment by ducnm9** [comment]
Please update BIOS

Verison >= 1.60 | 2020/9/9 | 10.72MB | Windows® | Optimized CPU core performance


https://www.asrock.com/MB/Intel/B460M%20Steel%20Legend/index.asp#BIOS

**Comment by RMXdo** [comment]
Hello, I have updated to the latest Bios, but problem still persists.

**Comment by bali888888** [comment]
I actually solve the problem by reconfigure the GPU, need to use the hackintools to config the gpu id

**Comment by RMXdo** [comment]
> I actually solve the problem by reconfigure the GPU, need to use the hackintools to config the gpu id"

what should I do exactly?
