### ISSUE TITLE
Main B460 Steel Legend lỗi led

### ISSUE THREAD

**Issue by togari9x** [ducnm9/Hackintosh-Intel-i5-10400-Asrock-B460M-Steel-Legend#2]
Main B460M Steel Legend bị lỗi led sau khi hackintosh, không biết anh có gặp trường hợp nay không?

**Comment by anhnvme** [comment]
Bạn vào mainboard =>  advanced  => chipset config => deep sleep => Enable S4/S5.
Còn 1 dòng nữa mình k nhớ, đại khái ngay phía dưới dòng deep sleep, có tên hình như là turn on led in S5 => off
Mình đã fix theo cách này và thành công. không liên quan tới hackintosh

**Comment by togari9x** [comment]
![IMG_20200825_192223(1)](https://user-images.githubusercontent.com/69443662/91174908-24203080-e70a-11ea-94f6-847983cb450e.jpg)
mình follow theo hướng dẫn của bạn nhưng vẫn gặp lỗi, không biết trước đây bạn có gặp thông báo này không?

**Comment by anhnvme** [comment]
Lỗi này mình cũng đang gặp phải, khỏi chỉnh led luôn, main này đang bị lỗi chỉnh led. còn vụ tắt led khi tắt máy thì làm theo hướng dẫn của mình là được. hoặc bạn chuyển qua main z490 steel legend nhé, cài được hack, có sẵn EFI

**Comment by togari9x** [comment]
giờ bảo đổi main thì khoai :( đến mang đi BH mình còn ngại ấy chứ, thôi chấp nhận chỉnh led bằng điều khiển, đợi Asrock update bios fix vậy

**Comment by anhnvme** [comment]
> giờ bảo đổi main thì khoai :( đến mang đi BH mình còn ngại ấy chứ, thôi chấp nhận chỉnh led bằng điều khiển, đợi Asrock update bios fix vậy

dòng b460 cũng mới quá, nên cũng nằm chờ thôi, led mình còn cắm hết vào main cơ. k có cái điều khiển nào luôn :v

**Comment by togari9x** [comment]
> > giờ bảo đổi main thì khoai :( đến mang đi BH mình còn ngại ấy chứ, thôi chấp nhận chỉnh led bằng điều khiển, đợi Asrock update bios fix vậy
> 
> dòng b460 cũng mới quá, nên cũng nằm chờ thôi, led mình còn cắm hết vào main cơ. k có cái điều khiển nào luôn :v

khoai =)) đợt mua cũng chủ quan ko check trc, chứ lỗi led này main Asrock dính nhiều lắm, mấy đời gần đây đều bị. Cơ bản máu build case trắng, mà dòng b460 có mỗi con này

**Comment by anhnvme** [comment]
đồng râm, mình cũng case full trắng =]]. k có chuyển qua gigabyte hoặc msi :D

**Comment by togari9x** [comment]
yes, ko phải build case trắng thì múc giga rồi mà :D hack ổn định, giá lại rẻ hơn, nằm im thở khẽ chờ Asrock vậy

**Comment by anhnvme** [comment]
> yes, ko phải build case trắng thì múc giga rồi mà :D hack ổn định, giá lại rẻ hơn, nằm im thở khẽ chờ Asrock vậy

tối hôm qua mình về có test lại và fix được lỗi đèn led như sau. thay đổi vị trí jump led, trước mình cắm trên, giờ chuyển sang cắm dưới. kiểm tra lại jack đã được cắm đúng hoặc đang bị cắm lệch, main k nhận được tín hiệu led

sau đó cài lại windows, chưa update, lên trang chủ asrock, tải app shop, cho nó cài toàn bộ driver cần thiết. cài app điều chỉnh led, không mở lên vội, reboot. rồi mở lên và điều chỉnh bình thường.

sau đó update windows và cài các phần mềm cần thiết, hạn chế quá nhiều phần mềm điều chỉnh led trên PC.
trước mình cài gigabyte ( cho card amd ), icue (cho ram corsair ). nên có thể bị xung đột. 

Thử lại cách trên xem sao nhé

**Comment by togari9x** [comment]
okay, cám ơn bạn. Cuối tuần này mình thử lại xem sao 👍

**Comment by anhnvme** [comment]
Chia buồn =]], hôm qua đi làm về bật máy lên, => mất led tiếp theo. chắc là mua led ngoài thôi, led main coi như bỏ :D
https://shopee.vn/Bộ-điều-khiển-led-RGB-5v-3-Pin-Kèm-Điều-Khiển-Không-Dây-i.191817934.7820529484

**Comment by togari9x** [comment]
haha :)) toàn đồng râm mua main phải con main lỗi vkl, chịu khó mua led ngoài thôi, mặc dù preset màu nó như pussy vậy

**Comment by anhnvme** [comment]
mình xài trắng thôi, k có nhu cầu rgb lắm :))

**Comment by anhnvme** [comment]
![IMG_0650](https://user-images.githubusercontent.com/13740754/91517023-1b507a00-e917-11ea-818a-7b1b2234222c.jpeg)
hình ảnh hiếm hoi khi lên đèn đẩy đủ :V

**Comment by togari9x** [comment]
![image](https://user-images.githubusercontent.com/69443662/91518065-80a56a80-e919-11ea-8c0f-41d3f551caed.png)

Haha hình lên full led lúc vừa lắp máy xong =)) sau đó main lỗi ko baoh sáng nữa, mà bạn mua pack fan ID Cooling giống mình, trong hộp có sẵn bộ điều khiển led mà nhỉ?! à xin info case nữa nhé

**Comment by anhnvme** [comment]
đồng râm ID Cooling =]. mình mua lẻ 3 chiếc, rẻ hơn 100k :))

**Comment by anhnvme** [comment]
case trước dùng xigmatek NYC, giờ chuyển qua xigmatek nemesis white rồi

**Comment by togari9x** [comment]
> case trước dùng xigmatek NYC, giờ chuyển qua xigmatek nemesis white rồi

con NYC bé quá hơi bí khí, nemesis lại là form ATX rồi, sau lên Thermaltake s100 snow ấy, airflow tốt lại có bản lề mở mặt kính tiện vl =))

**Comment by anhnvme** [comment]
thì mình chơi ATX mà, con NYC bé quá, k thích, thích nó mid tower, mấy con full thì k thích, nhìn nó bị to quá. để kiếm con Thermaltake snow size mid :D, bạn biết mã nào không

**Comment by togari9x** [comment]
![image](https://user-images.githubusercontent.com/69443662/91521848-e0544380-e922-11ea-8a5d-e0700e41b491.png)
S100 đấy bạn, mod Nam Air bên tinhte đang dùng con này, nhìn chym ưng thực sự =))

**Comment by anhnvme** [comment]
cái nguồn kia mã gì đó bạn ơi, nhìn thích vãi

**Comment by togari9x** [comment]
Ổng mod thêm con màn ở đó thôi =)) 
https://tinhte.vn/thread/do-them-man-hinh-vao-thung-may-de-hien-thong-so-pc-de-lam-va-hieu-qua-rat-dep-mat.3164998/

**Comment by anhnvme** [comment]
thanks thím, bookmark lại rồi, sau sẽ mod :v

**Comment by nglequduph** [comment]
Mình không xài card rời mà xài GPU, nó lên đc có cổng DP mà ko lên đc HDMI, vô chạy Viber và Photoshop và IOS Simulator thì bị crash do graphic driver. Admin có chiêu gì ko. Giúp mình với

**Comment by anhnvme** [comment]
> thanks thím, bookmark lại rồi, sau sẽ mod :v

![image](https://user-images.githubusercontent.com/13740754/91639209-2d2d3c80-ea3f-11ea-8b6b-700ff4a44975.png)

đã xử lý xong ngon lành =]]. full led

**Comment by anhnvme** [comment]
> Ổng mod thêm con màn ở đó thôi =))
> https://tinhte.vn/thread/do-them-man-hinh-vao-thung-may-de-hien-thong-so-pc-de-lam-va-hieu-qua-rat-dep-mat.3164998/

![image](https://user-images.githubusercontent.com/13740754/91639215-3d451c00-ea3f-11ea-86f0-15722316d7d9.png)
đã xử lý xong ngon lành rồi nha thím

**Comment by togari9x** [comment]
> > Ổng mod thêm con màn ở đó thôi =))
> > https://tinhte.vn/thread/do-them-man-hinh-vao-thung-may-de-hien-thong-so-pc-de-lam-va-hieu-qua-rat-dep-mat.3164998/
> 
> ![image](https://user-images.githubusercontent.com/13740754/91639215-3d451c00-ea3f-11ea-86f0-15722316d7d9.png)
> đã xử lý xong ngon lành rồi nha thím

dùng remote là ngon mà =)) tôi quẫn quá cũng tháo ra xài remote từ lâu r

**Comment by anhnvme** [comment]
> dùng remote là ngon mà =)) tôi quẫn quá cũng tháo ra xài remote từ lâu r

đang xài 2 cái RF, trùng tần sóng, nhưng lệch chức năng =]]. thím có hướng xử lý k, ví dụ như tắt thằng 3 pin, thì thằng 4 pin bật. LOL

**Comment by anhnvme** [comment]
> Ổng mod thêm con màn ở đó thôi =))
> https://tinhte.vn/thread/do-them-man-hinh-vao-thung-may-de-hien-thong-so-pc-de-lam-va-hieu-qua-rat-dep-mat.3164998/

đã đổi sang gigabyte b460m =]]. k lỗi led lại có repo OC 6.1 :)). bù trừ 200k. nhẹ cả người bác ạ :D

**Comment by togari9x** [comment]
Ngon, chúc mừng thím, giờ ngại tháo main ra đi đổi quá, thôi kệ mẹ đợi Asrock kíu vậy. Vẫn đang dùng OC 0.5.9 =)) đợi khi nào release Big Sur update 1 thể

**Comment by nhd2106** [comment]
hello các bác, mình đang chuẩn bị mua linh kiện để cài hackintosh.
specs của em định mua là: 
- gigabite 460M Aorus Pro,
- i5 10400,
- msi rx 580 amor,
- SSD WD SN750 M2 black,
- 2x8gb 2666 kingston hyperX fury,

các bác cho mình hỏi card wifi và bluetooth m.n mua ở đâu vậy ạ, nếu được cho em xin địa chỉ với.
em ở SG.
btw, trong case này thì main gigabyte ok hơn không ạ?
cảm ơn m.n

**Comment by togari9x** [comment]
> hello các bác, mình đang chuẩn bị mua linh kiện để cài hackintosh.
> specs của em định mua là:
> 
> * gigabite 460M Aorus Pro,
> * i5 10400,
> * msi rx 580 amor,
> * SSD WD SN750 M2 black,
> * 2x8gb 2666 kingston hyperX fury,
> 
> các bác cho mình hỏi card wifi và bluetooth m.n mua ở đâu vậy ạ, nếu được cho em xin địa chỉ với.
> em ở SG.
> btw, trong case này thì main gigabyte ok hơn không ạ?
> cảm ơn m.n

Main giga ngon nhất cho hack nhé, còn lại cấu hình này ok rồi, lưu ý main khác nên dùng file EFI này có thể lỗi, tìm hiểu kĩ.
Về Card wifi thì voz có thread trao đổi khá sôi nổi, bạn có thể đọc rồi tự cân đối tài chính mua con nào phù hợp: https://voz.vn/t/wifi-nao-cho-hackintosk.30964/

**Comment by nhd2106** [comment]
@togari9x  cảm ơn bác nhiều, trả lời tốc độ quá :D

**Comment by togari9x** [comment]
> @togari9x cảm ơn bác nhiều, trả lời tốc độ quá :D

Haha, đúng lúc rảnh :D

**Comment by ducnm9** [comment]
Em cũng không để ý led lắm. Vi em cho nó tự chạy ko chỉnh mấy :D
