### ISSUE TITLE
Internal speaker has no output sound

### ISSUE THREAD

**Issue by JianpingZeng** [ducnm9/Hackintosh-Intel-i5-10400-Asrock-B460M-Steel-Legend#8]
Hello,
I successfully ran hackintosh on my PC with same configuration except for asrock B460m Pro4 motherboard. However, selected internal speaker has no sound and I tried all layout id from 1 to 28 for ALC 1200 though. Airpods works well.
Best,
Jianping.

**Comment by nhd2106** [comment]
hi There,
you just use the newest version of open-core,
sound will work natively.
