### ISSUE TITLE
this EFI works with onboard HD630

### ISSUE THREAD

**Issue by bali888888** [ducnm9/Hackintosh-Intel-i5-10400-Asrock-B460M-Steel-Legend#9]

**Comment by bali888888** [comment]
I have used it and it works with DP onboard GPU HD630

**Comment by bali888888** [comment]
One issue with this EFI the DP audio can't be adjust by system up/down

**Comment by If-only1** [comment]
> One issue with this EFI the DP audio can't be adjust by system up/down
I tried it， it can't work with the HDMI onboard HD630

**Comment by ducnm9** [comment]
Sorry, i not using GPU HD630!  So sorry !!!!!
